# Generated by Django 3.0.5 on 2020-04-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasticcsample',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
